name: run-tests

on:
  pull_request: null
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.0, 7.4, 7.3, 7.2 ]
        dependency-version: [ prefer-lowest, prefer-stable ]

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: pocv

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: composer ci

      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.php }}
          path: build

  upload-coverage:
    needs:
      - test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.0, 7.4, 7.3, 7.2 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
      - uses: actions/download-artifact@v2
        with:
          name: build-${{ matrix.php }}
          path: build
      - name: Publish coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./build/clover.xml

  delete-artifacts:
    needs:
      - test
      - upload-coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.0, 7.4, 7.3, 7.2 ]
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: build-${{ matrix.php }}
